---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: local-test-centos
  namespace: flux-system
spec:
  interval: 15s
  path: ./test-files
  prune: true
  sourceRef:
    kind: GitRepository
    name: local-test-centos
  targetNamespace: flux-system
