---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: local-test-centos
  namespace: flux-system
spec:
  interval: 15s
  ref:
    branch: main
  url: https://github.com/roger-ding/local-fluxcd-test-files

