---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: local-test
  namespace: flux-system
spec:
  interval: 15s
  path: ./clusters/local-test-helm-flux-cluster/local-test
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-test
