---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: local-test
  namespace: default
spec:
  interval: 15s
  url: https://github.com/roger-ding/fluxcd-test
  ref:
    branch: main

