---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-test
  namespace: default 
spec:
  interval: 15s
  chart:
    spec:
      chart: ./clusters/local-test-helm-flux-cluster/local-test
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: fluxcd-test
        namespace: default
      interval: 15s

