---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-test
  namespace: flux-system
spec:
  chart:
    spec:
      chart: local-test
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: fluxcd-test
  interval: 15s

