apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-test 
  namespace: flux-system 
spec:
  interval: 15s
  chart:
    spec:
      chart: ./helm-charts
      sourceRef:
        kind: GitRepository
        name: local-test
        namespace: flux-system
      interval: 15s
