---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: local-test
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/local-test-flux-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-files
