apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
    - /bin/sh
    - -c
    - echo "Hello World!" && sleep infinity
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
