---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/charts/
  interval: 15s
  ref:
    branch: master
  url: https://github.com/roger-ding/podinfo

