---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/podinfo
      interval: 15s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: podinfo
  interval: 15s
  targetNamespace: flux-system

